//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public int MaPhieuNhap { get; set; }
        public string MaSP { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public int GiaNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public int SoLuongNhap { get; set; }
        public string TenSP { get; set; }
    
        public virtual KhoThuoc KhoThuoc { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
